# Generated by Django 5.0.7 on 2024-07-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Аттрибут', 'verbose_name_plural': 'Аттрибуты'},
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='attributes',
        ),
    ]
