# Generated by Django 5.0.7 on 2024-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_attribute_options_alter_attribute_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True, verbose_name='slug'),
        ),
    ]
