# Generated by Django 5.0.7 on 2024-09-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attribute_slug_categorymodel_slug_colormodel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.AddField(
            model_name='attribute',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии?'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productmodel', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colormodel',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии?'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.productmodel', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colormodel',
            name='product_image_id',
            field=models.CharField(default=1, max_length=100, verbose_name='ID фото продукта с таким цветом'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=130, null=True, unique=True, verbose_name='slug')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_cats', to='product.productmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Аттрибут',
                'verbose_name_plural': 'Аттрибуты',
                'db_table': 'attribute_cats',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.attributecategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
