# Generated by Django 5.0.7 on 2024-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_attribute_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributecategory',
            options={'verbose_name': 'Категория Аттрибутов', 'verbose_name_plural': 'Категории Аттрибутов'},
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='product_image_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID фото продукта с таким цветом'),
        ),
    ]
