# Generated by Django 5.0.7 on 2024-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_attributecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
