# Generated by Django 4.2.16 on 2024-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_colormodel_code_alter_colormodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='attributecategory',
            options={'verbose_name': 'Категория Параметров', 'verbose_name_plural': 'Категории Параметров'},
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='code',
        ),
        migrations.AddField(
            model_name='attribute',
            name='product_image_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID фото продукта с таким параметром'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='product_image_id',
            field=models.CharField(max_length=100, verbose_name='ID фото продукта с таким цветом'),
        ),
    ]
