# Generated by Django 4.2.16 on 2024-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_attribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormodel',
            name='product_image_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID фото продукта с таким цветом'),
        ),
    ]
