name: Deployment

on:
  push:
    branches:
      - dev
      - main

    paths-ignore:
      - "README.md"

jobs:
  deploy:
    name: Deploy

    runs-on: self-hosted

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Deploy using docker compose
        run: |
            cp ~/.secrets/.env .
            docker compose down
            docker compose up --build -d
            yes | docker image prune